routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes(['verify' => true]);

// Route::get('/register/getEmail',function(){
//     return redirect('login');
// });



// Route::post('register/getEmail','Auth\LoginController@setEmail')->name('set_email');
// Route::get('signin/{provider}', 'Auth\LoginController@redirectToProvider');
// Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/blog/{alias}','Frontend\BlogController@post')->name('blog');
Route::get('/blog','Frontend\BlogController@index');

Route::get('/', 'Frontend\PageController@home')->name('home');
Route::get('/landing3', 'Frontend\PageController@index3')->name('home');
Route::get('/landing4', 'Frontend\PageController@index4')->name('home');

Route::get('home', 'Frontend\PageController@home');

Route::get('/clients','Frontend\PageController@clients');
Route::post('newsletter/subscribe','Frontend\PageController@NewsLetter')->name('newsletter.subscribe');
Route::get('/category/{slug}/{sub_slug}','Frontend\PageController@category');
Route::get('/category/{slug}','Frontend\PageController@category');
Route::get('/about-us', 'Frontend\PageController@about');
Route::get('/privacy-policy', 'Frontend\PageController@privacyPolicy');
Route::get('/terms-and-conditions', 'Frontend\PageController@termsAndConditions');
Route::get('/inquiry', 'Frontend\PageController@inquiry');
Route::post('/inquiry/submit', 'Frontend\PageController@inquirySubmit');



// Route::get('/shop','Frontend\PageController@shop');

Route::get('/shop/{category_slug?}','Frontend\PageController@shop')->name('shop');

Route::get('/products/{slug}','Frontend\PageController@products');

Route::get('/search','Frontend\PageController@Search');
Route::get('/testimonials','Frontend\PageController@testimonials');
// Route::get('/contact',function(){
//     return view('frontend.contact');
// });
// Route::get('/about',function(){
//     $testimonials= Testimonial::all();
//     return view('frontend.about')->with('testimonials',$testimonials);
// });

Route::get('/cart','Frontend\CartController@cart');

Route::post('/cart/additem','Frontend\CartController@addItem');
Route::post('/cart/removeitem/{rowId}','Frontend\CartController@removeItem');
Route::post('/cart/emptycart','Frontend\CartController@emptyCart');
Route::post('/cart/updateqty','Frontend\CartController@updateQty');

Route::post('/checkout','Frontend\CheckoutController@shippingInformation');
Route::get('/checkout','Frontend\CheckoutController@summary');

Route::post("/payment/paypal", 'Frontend\CheckoutController@payWithPaypal');
Route::post("/payment/paypal/return", 'Frontend\CheckoutController@getPaypalPaymentStatus');

Route::get('payment/{code}','Frontend\CheckoutController@payment')->name('payment');
Route::post('payment/{code}','Frontend\CheckoutController@paymentSuccess')->name('payment');

Route::get('/order/{slug}','Frontend\PageController@Order');

Route::post('post/message','Frontend\PageController@Feedback')->name('contact.us');
Route::post('post/order','Frontend\PageController@GeneralOrder')->name('general.order');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/test', 'HomeController@index');

// Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
// Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
// Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');



Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');
    
    Route::get('manage/categories','Admin\CategoryController@index')->name('category.index');
    Route::get('manage/infos','Admin\InfoController@index')->name('infos.index');


    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    Route::post('settings/edit-socials','Admin\SettingsController@editSocials')->name('admin.settings.editSocials');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');
    
    //order Routes
    Route::get('quotations/all','Admin\QuotationController@allQuotations')->name('all.quotations');
    Route::post('quotations/delete','Admin\AdminController@DeleteQuotation')->name('delete.quotation');
    Route::get('quotations/export','Admin\QuotationController@export')->name('quotations.export');
    Route::get('quotations/{id}','Admin\AdminController@ShowQuotation')->name('show.quotation');
    Route::get('quotations','Admin\QuotationController@index')->name('quotations.index');
    Route::get('getUnseenQuotationCount','Admin\QuotationController@getUnseenOrderCount')->name('getUnseenQuotationCount');
    Route::get('getUnseenQuotation','Admin\QuotationController@getUnseenOrder')->name('getUnseenQuotation');
    Route::post('markseen/quotation','Admin\QuotationController@MarkSeen');

    Route::get('orders/all','Admin\OrderController@allOrders')->name('all.orders');
    Route::delete('orders/{id}/delete','Admin\AdminController@DeleteOrder')->name('orders.destroy');
    Route::get('orders/export','Admin\OrderController@export')->name('orders.export');
    Route::get('orders/{id}','Admin\AdminController@ShowOrder')->name('show.order');
    Route::patch('orders/{id}','Admin\OrderController@update')->name('orders.update');
    Route::get('orders','Admin\OrderController@index')->name('orders.index');
    Route::get('getUnseenOrderCount','Admin\OrderController@getUnseenOrderCount')->name('getUnseenOrderCount');
    Route::get('getUnseenOrder','Admin\OrderController@getUnseenOrder')->name('getUnseenOrder');
    Route::post('markseen/order','Admin\OrderController@MarkSeen');

    Route::resource('blogs', 'Admin\BlogController',['except' => ['create']]);

    Route::post('/testimonials/update-status','Admin\TestimonialController@updateStatus')->name('testimonials.activate');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::post('pages/{page}/update','Admin\PageController@update')->name('pages.update');
    Route::get('pages','Admin\PageController@index')->name('pages.index');

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
    
    //Category routes
    
    Route::post('/manage/categories','Admin\CategoryController@StoreCat')->name('category.add');
    Route::get('/edit/category/{id}','Admin\CategoryController@EditCat')->name('category.edit');
    Route::post('/update/category/{id}','Admin\CategoryController@UpdateCat')->name('category.update');
    Route::post('/delete/category/{id}','Admin\CategoryController@DestroyCat')->name('category.delete');
    
    Route::post('/edit/info','Admin\InfoController@EditInfo')->name('info.edit');
    
    
    Route::get('manage/clients','Admin\ClientController@index');

    Route::post('/manage/clients','Admin\ClientController@StoreCat')->name('client.add');
    Route::post('/edit/client','Admin\ClientController@EditCat')->name('client.edit');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('body')
<div class="content-header row">
    </div>
    <div class="content-body">
        {{-- <div class="text-xs-right">
            @if($s == 'all')
                <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="#">See all unseen Quotations</a>
            @else
                <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="#">See all quotations</a>
            @endif
        </div> --}}
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">New Orders</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>No. of Product</th>
                                    <th>Amount</th>
                                    <th>Order Status</th>
                                    <th>Payment Status</th>
                                    <th>Ordered Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($orders as $order)
                                    
                                    <tr>
                                        <th scope="row">{{ $order->id }}</th>
                                        <td>{{ $order->items()->where('type','Product')->count() }}</td>
                                        <td>AED {{ number_format($order->amount) }}</td>
                                        <td><span class="tag {{ ($order->status == 'delivered') ? 'tag-success': ($order->order_status == 'cancelled' ? 'tag-danger' : 'tag-warning') }}">{{ $order->status }}</span></td>
                                        <td><span class="tag {{ ($order->paid  ? 'tag-success': 'tag-danger') }}">{{ $order->paid ? 'Paid' : 'Unpaid' }}</span></td>
                                        <td>{{ date('M j, Y',strtotime($order->ordered_at)) }}</td>

                                        <td>
                                            <a class="btn btn-outline-info btn-sm" title="View" href="{{route('show.order',$order->id)}}"><i class="icon-eye"></i></a>
                                            <form action="{{ route('orders.destroy',$order->id) }}" method="POST" style="display:inline">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="_method" value="DELETE" >
                                                <button id='deleteOrder{{ $order->id }}' type="button" title="Delete" class="btn btn-sm btn-outline-danger"><i class="icon-trash-o"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        
                        <div class="text-xs-center mb-3">
                            <nav aria-label="Page navigation">
                                {{ $orders->appends('quotations', \Request::get('quotations',1))->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">New Quotation Messages</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Quotationed Product</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($quotations as $quotation)
                                {{-- @if(!$contact->seen && $state == 'all')
                                    <tr style="background:#d6d3d3">
                                @else
                                    <tr>
                                @endif --}}
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $quotation->name }}</td>
                                    <td>{{ $quotation->product_name }}</td>
                                    <td>
                                    <a class="btn btn-outline-info btn-sm" title="View" href="{{route('show.quotation',$quotation->id)}}"><i class="icon-eye"></i></a>
                                        <a id='deleteQuotation{{$quotation->id}}' title="delete" type="button" class="btn btn-outline-danger btn-sm"><i class="icon-trash-o"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{-- @if(count($contacts)==0)
                            <p class="font-medium-3 text-muted text-xs-center" style="margin:100px">No {{ $state == 'all'?'':'New'}} Messages</p>
                        @endif --}}
                        <div class="text-xs-center mb-3">
                            <nav aria-label="Page navigation">
                                {{ $quotations->appends('orders', \Request::get('orders',1))->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

@section('js')
<script>
    $(document).on('click',"[id*='deleteQuotation']",function(event){
        var id = $(this).attr("id").slice(11);
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this file!",
            type: "warning",
    
            showCancelButton: true,
    
          }).then(function(){
            $.post("{{route('delete.quotation')}}",{id:id,_token:"{{csrf_token()}}"},function(data){
              swal({
                title:"Deleted Successfully",
                type:"success"
    
              }).then(function(){
               location.reload();
              })
            })
          });
    });
    </script>

@endsection

resources/views/admin/newsletter.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Create Newsletter</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('newsletterSend') }}"  enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input name="image" type="file" id="upload" class="hidden" onchange="">

                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" class="form-control{{ $errors->has('subject') ? ' border-danger' : '' }}" id="subject" name="subject">
                            @if ($errors->has('subject'))
                                <div class="alert alert-danger no-border mb-2">
                                    <strong>{{ $errors->first('subject') }}</strong>
                                </div>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="attachment">Attachment</label>
                            <input type="file" class="form-control" id="attachment" name="attachment">
                        </div>

                        <div class="form-group">
                            <label for="message">Message <span style="color:red;font-size:25px;">*</span></label>
                            @if ($errors->has('message'))
                                <div class="alert alert-danger no-border mb-2">
                                    <strong>{{ $errors->first('message') }}</strong>
                                </div>
                            @endif
                            <textarea cols="50" rows="20" class="form-control{{ $errors->has('message') ? ' border-danger' : '' }}" id="message" name="message"></textarea>
                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea#message",
           
           plugins: [
               "advlist autolink lists link image charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
           toolbar2: "print preview | forecolor backcolor emoticons | template",
           image_advtab: true,
           file_picker_callback: function(callback, value, meta) {
           if (meta.filetype == 'image') {
               $('#upload').trigger('click');
               $('#upload').on('change', function() {
               var file = this.files[0];
               var reader = new FileReader();
               reader.onload = function(e) {
                   callback(e.target.result, {
                   alt: ''
                   });
               };
               reader.readAsDataURL(file);
               });
           }
           },
           templates: [
               {title: 'Newsletter1', description: 'Notice', url: "/templates/newsletter.html"}
             ]
       });
   </script>
  
@endsection

resources/views/admin/testimonials.blade.php
@extends('layouts.admin')

@section('body')
    <style>
        .switch input { 
            display:none;
        }
        .switch {
            display:inline-block;
            width:30px;
            height:15px;
            margin:8px;
            transform:translateY(50%);
            position:relative;
        }
        
        .slider {
            position:absolute;
            top:0;
            bottom:0;
            left:0;
            right:0;
            border-radius:15px;
            box-shadow:0 0 0 2px #777, 0 0 4px #777;
            cursor:pointer;
            border:4px solid transparent;
            overflow:hidden;
            transition:.4s;
        }
        .slider:before {
            position:absolute;
            content:"";
            width:100%;
            height:100%;
            background:#777;
            border-radius:15px;
            transform:translateX(-15px);
            transition:.4s;
        }
        
        input:checked + .slider:before {
            transform:translateX(15px);
            background:limeGreen;
        }
        input:checked + .slider {
            box-shadow:0 0 0 2px limeGreen,0 0 2px limeGreen;
        }
        
    </style>

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Testimonials</h2>
        </div>
    </div>
    <div class="row match-height">
        <div class="col-xl-4 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-block">
                    @if($state == 'Add')
                        <form class="form" method="POST" action="{{ route('testimonials.store') }}"  enctype="multipart/form-data">
                    @else
                        <form class="form" method="POST" action="{{ route('testimonials.update',$testimonial_->id) }}"  enctype="multipart/form-data">                            
                        <input type="hidden" name="_method" value="PATCH" >
                    @endif
                            {{ csrf_field() }}
                            
                            <div class="form-group">
                                <label for="name"><strong>Name:</strong></label>
                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="name" class="form-control" name="name" value="{{ $testimonial_->name }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="profession"><strong>Profession:</strong></label>
                                @if ($errors->has('profession'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('profession') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="profession" class="form-control" name="profession" value="{{ $testimonial_->profession }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="photo"><strong>{{ $state=='Add'?'':'Current ' }}Image <span class="text-muted">(Optional)</span>: </strong></label> {{ $testimonial_->photo }}
                                @if ($errors->has('photo'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('photo') }}</strong>
                                    </div>
                                @endif
                                <input type="file" id="photo" class="form-control" name="photo"/>
                            </div>
                            <div class="form-group">
                                <label><strong>New Testimonial:</strong></label>
                                @if ($errors->has('content'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </div>
                                @endif
                            
                                <textarea class="form-control" rows='6' id="content" name="content" required>{{ $testimonial_->content }}</textarea>

                            </div>
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> {{ $state=="Add"?"Add New":"Save" }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @foreach($testimonials as $testimonial)
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-block">
                            <h4 class="card-title">{{ $testimonial->name }}</h4>
                            <h6 class="card-subtitle text-muted">{{ $testimonial->profession }}</h6>
                            @if($testimonial->photo)
                                <img class="img-fluid my-1" src="{{ route('optimize', ['landing_images',$testimonial->photo,290,290]) }}" alt="Card image cap">
                            @else
                                <img class="img-fluid my-1" src="{{ route('optimize', ['img','avatar.png',290,290]) }}" alt="{{ $testimonial->name }}"/>
                            @endif
                            <p class="card-text">{{ $testimonial->content }}</p>

                            <div class="mb-2">
                                <label class="switch">
                            
                                    <input id="activate{{$testimonial->id}}" type="checkbox"
                                    @if($testimonial->active == true)
                                        checked
                                    @endif
                                    >
                                    <span class="slider"></span>
                                </label>
                                <span><b>Active</b></span>
                            </div>
                            <a href="{{ route('testimonials.edit',$testimonial->id) }}" class="btn btn-outline btn-warning">Edit</a>
                            
                            <form action="{{ route('testimonials.destroy',$testimonial->id) }}" style="display:inline" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE" >
                                <button id='deleteTestimonial' type="button" class="btn btn-outline btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

@section('js')
    <script>
        $("[id*='delete']").click(function(e){
            var ele = this;
            e.preventDefault();
            
            swal({
            title: "Are you sure?",
            text: "You will not be able to recover this record!",
            type: "warning",

            showCancelButton: true,

            }).then(function(){
            ele.form.submit();
            }).catch(swal.noop);

        });

        $(document).on('click',"[id*='activate']",function(event){
            var id = $(this).attr("id").slice(8);
            $.ajax({
                type: "POST",
                url: "{{ route('testimonials.activate') }}",
                data: { 
                    id: id,
                    _token:"{{csrf_token()}}"
                },
                success: function(result) {
                
                },
                error: function(result) {
                    alert('Something went wrong.');
                }
            });
        });
  </script>
@endsection