routes/web.php
Route::post('/cart/removeitem/{rowId}','Frontend\CartController@removeItem');
Route::post('/cart/emptycart','Frontend\CartController@emptyCart');
Route::post('/cart/updateqty','Frontend\CartController@updateQty');

Route::post('/checkout','Frontend\CheckoutController@shippingInformation');
Route::get('/checkout','Frontend\CheckoutController@summary');

Route::post("/payment/paypal", 'Frontend\CheckoutController@payWithPaypal');
Route::post("/payment/paypal/return", 'Frontend\CheckoutController@getPaypalPaymentStatus');

Route::get('payment/{code}','Frontend\CheckoutController@payment')->name('payment');
Route::post('payment/{code}','Frontend\CheckoutController@paymentSuccess')->name('payment');

Route::get('/order/{slug}','Frontend\PageController@Order');

Route::post('post/message','Frontend\PageController@Feedback')->name('contact.us');
Route::post('post/order','Frontend\PageController@GeneralOrder')->name('general.order');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/test', 'HomeController@index');

// Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
// Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
// Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');



Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');
    
    Route::get('manage/categories','Admin\CategoryController@index')->name('category.index');
    Route::get('manage/infos','Admin\InfoController@index')->name('infos.index');


    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    Route::post('settings/edit-socials','Admin\SettingsController@editSocials')->name('admin.settings.editSocials');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');
    
    //order Routes
    Route::get('quotations/all','Admin\QuotationController@allQuotations')->name('all.quotations');
    Route::post('quotations/delete','Admin\AdminController@DeleteQuotation')->name('delete.quotation');
    Route::get('quotations/export','Admin\QuotationController@export')->name('quotations.export');
    Route::get('quotations/{id}','Admin\AdminController@ShowQuotation')->name('show.quotation');
    Route::get('quotations','Admin\QuotationController@index')->name('quotations.index');
    Route::get('getUnseenQuotationCount','Admin\QuotationController@getUnseenOrderCount')->name('getUnseenQuotationCount');
    Route::get('getUnseenQuotation','Admin\QuotationController@getUnseenOrder')->name('getUnseenQuotation');
    Route::post('markseen/quotation','Admin\QuotationController@MarkSeen');

    Route::get('orders/all','Admin\OrderController@allOrders')->name('all.orders');
    Route::delete('orders/{id}/delete','Admin\AdminController@DeleteOrder')->name('orders.destroy');
    Route::get('orders/export','Admin\OrderController@export')->name('orders.export');
    Route::get('orders/{id}','Admin\AdminController@ShowOrder')->name('show.order');
    Route::patch('orders/{id}','Admin\OrderController@update')->name('orders.update');
    Route::get('orders','Admin\OrderController@index')->name('orders.index');
    Route::get('getUnseenOrderCount','Admin\OrderController@getUnseenOrderCount')->name('getUnseenOrderCount');
    Route::get('getUnseenOrder','Admin\OrderController@getUnseenOrder')->name('getUnseenOrder');
    Route::post('markseen/order','Admin\OrderController@MarkSeen');

    Route::resource('blogs', 'Admin\BlogController',['except' => ['create']]);

    Route::post('/testimonials/update-status','Admin\TestimonialController@updateStatus')->name('testimonials.activate');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::post('pages/{page}/update','Admin\PageController@update')->name('pages.update');
    Route::get('pages','Admin\PageController@index')->name('pages.index');

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
    
    //Category routes
    
    Route::post('/manage/categories','Admin\CategoryController@StoreCat')->name('category.add');
    Route::get('/edit/category/{id}','Admin\CategoryController@EditCat')->name('category.edit');
    Route::post('/update/category/{id}','Admin\CategoryController@UpdateCat')->name('category.update');
    Route::post('/delete/category/{id}','Admin\CategoryController@DestroyCat')->name('category.delete');
    
    Route::post('/edit/info','Admin\InfoController@EditInfo')->name('info.edit');
    
    
    Route::get('manage/clients','Admin\ClientController@index');

    Route::post('/manage/clients','Admin\ClientController@StoreCat')->name('client.add');
    Route::post('/edit/client','Admin\ClientController@EditCat')->name('client.edit');
    Route::post('/delete/client','Admin\ClientController@DestroyCat')->name('client.delete');
    Route::post('/client/feature','Admin\ClientController@FeatureClient');

    Route::get('/downloads','Admin\DownloadController@index')->name('downloads.index');
    Route::post('/downloads','Admin\DownloadController@store')->name('download.add');
    Route::post('/edit/download','Admin\DownloadController@update')->name('download.update');
    Route::post('/delete/download','Admin\DownloadController@destroy')->name('download.delete');

    Route::get('/deliveryzones','Admin\DeliveryZoneController@index')->name('delivery_zones.index');
    Route::post('/deliveryzones','Admin\DeliveryZoneController@store')->name('delivery_zone.add');
    Route::post('/edit/delivery_zone','Admin\DeliveryZoneController@update')->name('delivery_zone.update');
    Route::post('/delete/delivery_zone','Admin\DeliveryZoneController@destroy')->name('delivery_zone.delete');
    
    //subcategory routes
    Route::post('/manage/subcategories','Admin\CategoryController@StoreSubCat')->name('subcategory.add');
    Route::post('/delete/subcategory','Admin\CategoryController@DestroySubCat')->name('subcategory.delete');
    Route::post('/edit/subcategory','Admin\CategoryController@EditSubCat')->name('subcategory.edit');
    
    Route::resource('brands', 'Admin\BrandController',['except' => ['create','show']]);

    Route::resource('tags', 'Admin\TagController',['only' => ['index','store','update','destroy']]);

    //Product routes
    Route::get('/product-subcat/{id}','Admin\ProductController@getSubCat');
    Route::get('/filter/products/{subcat_id}','Admin\ProductController@FilterProduct');
    Route::post('/product/feature','Admin\ProductController@FeatureProduct');
    Route::post('/product/activate','Admin\ProductController@ActivateProduct');
    Route::post('/product/showinslider','Admin\ProductController@ShowInSliderProduct');
    Route::post('product/image/delete','Admin\ProductController@RemoveProductImage')->name('productimage.delete');
    Route::resource('products', 'Admin\ProductController',['except' => ['show']]);
    
    Route::get('seo-settings/{page}','Admin\SettingsController@page')->name('admin.seo-settings');
    Route::post('seo-settings/{page}/update','Admin\SettingsController@pageUpdate')->name('admin.seo-settings.update');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Brand extends Model
{
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Brand;

class BrandController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index()
    {
        $brands = Brand::orderBy('updated_at','desc')->paginate(10);
        
        return view('admin.brands.index')->with('brands',$brands);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([         
            'name' => 'required|max:191',
            'logo' => 'nullable|image',
        ]);
        
        $brand = new Brand;
        $brand->name = $request->name;

        if($request->hasFile('logo')){
            $photo = $request->file('logo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            $location = public_path('brand_logos/');
            $photo->move($location,$filename);
            $brand->logo = $filename;
        }

        $brand->save();

        $request->session()->flash('success', 'Brand added.');        
        
        return redirect()->route('brands.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brand = Brand::findOrFail($id);

        return view('admin.brands.edit',compact('brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([         
            'name' => 'required|max:191',
            'logo' => 'nullable|image',
        ]);

        $brand = Brand::findOrFail($id);
        $brand->name = $request->name;     

        if($request->hasFile('logo')){

            if($brand->logo)
                unlink(public_path('brand_logos/'.$brand->logo));

            $photo = $request->file('logo');
            $filename = time() . '.' . $photo->getClientOriginalExtension();
            $location = public_path('brand_logos/');
            $photo->move($location,$filename);
            $brand->logo = $filename;
        }

        $brand->save();

        $request->session()->flash('success', 'Brand updated.');        
        
        return redirect()->route('brands.index');
    }

    public function destroy(Request $request, $id)
    {
        $brand = Brand::findOrFail($id);

        if($brand->file)
            unlink(public_path('brand_logos/'.$brand->file));
            
        $brand->delete();

        $request->session()->flash('success', 'Brand deleted.');        
        
       return redirect()->back();
    }
}

resources/views/admin/brands/edit.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Edit Brand</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('brands.update',$brand->id) }}"  enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PATCH" >

                        <div class="form-body">

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" class="form-control" name="name" value="{{ $brand->name }}" required>

                                        @if ($errors->has('name'))
                                            <div class="alert alert-danger no-border mb-2">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Logo (Optional)</label>
                                <input class="form-control{{ $errors->has('logo') ? ' border-danger' : '' }}" type="file" placeholder="File"  name="logo">

                                @if ($errors->has('logo'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('logo') }}</strong>
                                    </div>
                                @endif
                                @if($brand->logo) 
                                    Current Logo:
                                    
                                    <img src="{{ '/brand_logos/'.$brand->logo }}" style="max-height: 5rem"/>
                                
                                @endif
                            </div>
                        </div>

                        <div class="form-actions right">
                            <a class="btn btn-warning" href="{{ route('brands.index') }}">Cancel</a>

                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea.content",
           
           plugins: [
               "advlist autolink lists link charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link",
           toolbar2: "print preview | forecolor backcolor emoticons"
       });
   </script>
  
@endsection

resources/views/admin/brands/index.blade.php
@extends('layouts.admin')

@section('body')
   
    <div class="content-header row">

    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a data-action="collapse">Add New Brand</a></h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="{{ count($errors)>0 ? 'icon-minus4':'icon-plus4' }}"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse {{ count($errors)>0 ? 'in':'out' }}">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" id="AddBlogForm" action="{{ route('brands.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-body">
                                <h4 class="form-section"><i class="icon-eye6"></i> Brand</h4>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Name</label>
                                            <input class="form-control{{ $errors->has('name') ? ' border-danger' : '' }}" id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required>

                                            @if ($errors->has('name'))
                                                <div class="alert alert-danger no-border mb-2">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Logo (Optional)</label>
                                    <input class="form-control{{ $errors->has('logo') ? ' border-danger' : '' }}" type="file" placeholder="File"  name="logo">

                                    @if ($errors->has('logo'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('logo') }}</strong>
                                        </div>
                                    @endif
                                </div>
                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Brands</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Products</th>
                                    <th>Logo</th>
                                    <th width="20%">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($brands as $brand)
                                <tr>
                                    <td>{{ $loop->iteration + (($brands->currentPage()-1) * $brands->perPage()) }}</td>
                                    <td>{{ $brand->name }}</td>
                                    <td>{{ $brand->products()->count() }}</td>
                                    <td>
                                            @if($brand->logo) 
                                                <img src="{{ '/brand_logos/'.$brand->logo }}" style="max-height: 3rem"/>
                                            @else 
                                                - 
                                            @endif
                                        </td>
                                    <td>

                                        <a class="btn btn-outline-warning" title="Update Details" href="{{ route('brands.edit',$brand->id) }}"><i class="icon-edit"></i></a>
                                        
                                        <form action="{{ route('brands.destroy',$brand->id) }}" method="POST" style="display:inline">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE" >
                                            <button id='deleteBrand{{ $brand->id }}' type="button" class="btn btn-outline-danger"><i class="icon-trash-o"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>


                        <div class="text-xs-center mb-3">
                            <nav aria-label="Page navigation">
                                {{ $brands->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

   
@endsection

@section('js')
  
@endsection