routes/web.php
Route::post('/cart/removeitem/{rowId}','Frontend\CartController@removeItem');
Route::post('/cart/emptycart','Frontend\CartController@emptyCart');
Route::post('/cart/updateqty','Frontend\CartController@updateQty');

Route::post('/checkout','Frontend\CheckoutController@shippingInformation');
Route::get('/checkout','Frontend\CheckoutController@summary');

Route::post("/payment/paypal", 'Frontend\CheckoutController@payWithPaypal');
Route::post("/payment/paypal/return", 'Frontend\CheckoutController@getPaypalPaymentStatus');

Route::get('payment/{code}','Frontend\CheckoutController@payment')->name('payment');
Route::post('payment/{code}','Frontend\CheckoutController@paymentSuccess')->name('payment');

Route::get('/order/{slug}','Frontend\PageController@Order');

Route::post('post/message','Frontend\PageController@Feedback')->name('contact.us');
Route::post('post/order','Frontend\PageController@GeneralOrder')->name('general.order');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/test', 'HomeController@index');

// Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
// Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
// Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');



Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');
    
    Route::get('manage/categories','Admin\CategoryController@index')->name('category.index');
    Route::get('manage/infos','Admin\InfoController@index')->name('infos.index');


    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    Route::post('settings/edit-socials','Admin\SettingsController@editSocials')->name('admin.settings.editSocials');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');
    
    //order Routes
    Route::get('quotations/all','Admin\QuotationController@allQuotations')->name('all.quotations');
    Route::post('quotations/delete','Admin\AdminController@DeleteQuotation')->name('delete.quotation');
    Route::get('quotations/export','Admin\QuotationController@export')->name('quotations.export');
    Route::get('quotations/{id}','Admin\AdminController@ShowQuotation')->name('show.quotation');
    Route::get('quotations','Admin\QuotationController@index')->name('quotations.index');
    Route::get('getUnseenQuotationCount','Admin\QuotationController@getUnseenOrderCount')->name('getUnseenQuotationCount');
    Route::get('getUnseenQuotation','Admin\QuotationController@getUnseenOrder')->name('getUnseenQuotation');
    Route::post('markseen/quotation','Admin\QuotationController@MarkSeen');

    Route::get('orders/all','Admin\OrderController@allOrders')->name('all.orders');
    Route::delete('orders/{id}/delete','Admin\AdminController@DeleteOrder')->name('orders.destroy');
    Route::get('orders/export','Admin\OrderController@export')->name('orders.export');
    Route::get('orders/{id}','Admin\AdminController@ShowOrder')->name('show.order');
    Route::patch('orders/{id}','Admin\OrderController@update')->name('orders.update');
    Route::get('orders','Admin\OrderController@index')->name('orders.index');
    Route::get('getUnseenOrderCount','Admin\OrderController@getUnseenOrderCount')->name('getUnseenOrderCount');
    Route::get('getUnseenOrder','Admin\OrderController@getUnseenOrder')->name('getUnseenOrder');
    Route::post('markseen/order','Admin\OrderController@MarkSeen');

    Route::resource('blogs', 'Admin\BlogController',['except' => ['create']]);

    Route::post('/testimonials/update-status','Admin\TestimonialController@updateStatus')->name('testimonials.activate');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::post('pages/{page}/update','Admin\PageController@update')->name('pages.update');
    Route::get('pages','Admin\PageController@index')->name('pages.index');

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
    
    //Category routes
    
    Route::post('/manage/categories','Admin\CategoryController@StoreCat')->name('category.add');
    Route::get('/edit/category/{id}','Admin\CategoryController@EditCat')->name('category.edit');
    Route::post('/update/category/{id}','Admin\CategoryController@UpdateCat')->name('category.update');
    Route::post('/delete/category/{id}','Admin\CategoryController@DestroyCat')->name('category.delete');
    
    Route::post('/edit/info','Admin\InfoController@EditInfo')->name('info.edit');
    
    
    Route::get('manage/clients','Admin\ClientController@index');

    Route::post('/manage/clients','Admin\ClientController@StoreCat')->name('client.add');
    Route::post('/edit/client','Admin\ClientController@EditCat')->name('client.edit');
    Route::post('/delete/client','Admin\ClientController@DestroyCat')->name('client.delete');
    Route::post('/client/feature','Admin\ClientController@FeatureClient');

    Route::get('/downloads','Admin\DownloadController@index')->name('downloads.index');
    Route::post('/downloads','Admin\DownloadController@store')->name('download.add');
    Route::post('/edit/download','Admin\DownloadController@update')->name('download.update');
    Route::post('/delete/download','Admin\DownloadController@destroy')->name('download.delete');

    Route::get('/deliveryzones','Admin\DeliveryZoneController@index')->name('delivery_zones.index');
    Route::post('/deliveryzones','Admin\DeliveryZoneController@store')->name('delivery_zone.add');
    Route::post('/edit/delivery_zone','Admin\DeliveryZoneController@update')->name('delivery_zone.update');
    Route::post('/delete/delivery_zone','Admin\DeliveryZoneController@destroy')->name('delivery_zone.delete');
    
    //subcategory routes
    Route::post('/manage/subcategories','Admin\CategoryController@StoreSubCat')->name('subcategory.add');
    Route::post('/delete/subcategory','Admin\CategoryController@DestroySubCat')->name('subcategory.delete');
    Route::post('/edit/subcategory','Admin\CategoryController@EditSubCat')->name('subcategory.edit');
    
    Route::resource('brands', 'Admin\BrandController',['except' => ['create','show']]);

    Route::resource('tags', 'Admin\TagController',['only' => ['index','store','update','destroy']]);

    //Product routes
    Route::get('/product-subcat/{id}','Admin\ProductController@getSubCat');
    Route::get('/filter/products/{subcat_id}','Admin\ProductController@FilterProduct');
    Route::post('/product/feature','Admin\ProductController@FeatureProduct');
    Route::post('/product/activate','Admin\ProductController@ActivateProduct');
    Route::post('/product/showinslider','Admin\ProductController@ShowInSliderProduct');
    Route::post('product/image/delete','Admin\ProductController@RemoveProductImage')->name('productimage.delete');
    Route::resource('products', 'Admin\ProductController',['except' => ['show']]);
    
    Route::get('seo-settings/{page}','Admin\SettingsController@page')->name('admin.seo-settings');
    Route::post('seo-settings/{page}/update','Admin\SettingsController@pageUpdate')->name('admin.seo-settings.update');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Cviebrock\EloquentSluggable\Sluggable;

class Tag extends Model
{
    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Tag;

class TagController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index()
    {
        $tags = Tag::orderBy('updated_at','desc')->paginate(10);
        
        return view('admin.tags.index')->with('tags',$tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([         
            'name' => 'required|unique:tags,name|max:191'
        ]);
        
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        $request->session()->flash('success', 'Tag added.');        
        
        return redirect()->route('tags.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([         
            'name' => 'required|max:191|unique:tags,name,' . $id
        ]);

        $tag = Tag::findOrFail($id);
        $tag->name = $request->name;

        $tag->save();

        $request->session()->flash('success', 'Tag updated.');        
        
        return redirect()->route('tags.index');
    }

    public function destroy(Request $request, $id)
    {
        $tag = Tag::findOrFail($id);
            
        $tag->delete();

        $request->session()->flash('success', 'Tag deleted.');        
        
       return redirect()->back();
    }
}

resources/views/admin/tags/index.blade.php
@extends('layouts.admin')

@section('body')
       
    <div class="content-body">
        <section id="addtags">  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title" ><a data-action="collapse"><h3>Tags</h3><h6>Add, Edit or Remove tags</h6>  </a></div>
                            <a class="heading-elements-toggle">
                                <i class="icon-ellipsis font-medium-3"></i>
                            </a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body  collapse in"> <!-- // collapse -->
                            <div class="card-block">
                                <div class="row col-md-12">
                                    <div style="padding-bottom:20px">
                                        <form class="form" method="POST" action="{{ route('tags.store') }}">
                                            {{ csrf_field() }}
                                            <div class="row">
                                                <div class="form-body">
                                                    <div class="form-group col-sm-3">
                                                        <input type="text" class="form-control" placeholder="Add New Tag" name="name" required>
                                                        
                                                    </div>

                                                    <div class="form-group  col-sm-3">
                                                        <button type="submit" class="btn btn-success">
                                                            <i class="icon-check2">Add</i> 
                                                        </button>
                                                    </div>  
                                                </div>
                                                @if ($errors->has('name'))
                                                    <div class="alert alert-danger no-border mb-2">
                                                        <strong>{{ $errors->first('name') }}</strong>
                                                    </div>
                                                @endif
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        @if(count($tags) == 0)
                                            <h6 style="text-align:  center;margin: 50px;">No tag added yet.</h6>
                                        @else
                                            <div class="table-responsive ">
                                                
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 40%">Tag Name</th>
                                                            <th style="width: 10%">Products</th>
                                                            <th style="width: 20%">Actions</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach($tags as $c)
                                                            <tr>
                                                                <td class="text-middle">
                                                                    <h4 id="categoryName{{ $c->id }}">{{$c->name}} </h4>
                                                                    
                                                                    <div id="CatupdateDiv{{$c->id}}" hidden>
                                                                        <form class="form" method="POST" action="{{ route('tags.update',$c->id) }}">
                                                                            <div class="row form-body">
                                                                                <div class="form-group col-sm-6">
                                                                                    {{csrf_field()}}
                                                                                    <input hidden name="_method" value="PATCH">

                                                                                    <input type="text" class="form-control" placeholder="Edit Name" name="name" value="{{ $c->name }}" required> 
                                                                                </div>
                                                                                <div class="form-group col-sm-6">
                                                                                    <button type="submit" class="btn btn-blue"> 
                                                                                        <i class="icon-check2"></i> 
                                                                                    </button>

                                                                                    <button class="btn btn-red" type="button" id="Catcancel{{ $c->id }}">
                                                                                        <i class="icon-cross"></i>
                                                                                    </button>          
                                                                                </div>
                                                                            </div> 
                                                                        </form>
                                                                    </div>
                                                                </td>
                                                                <td>{{ $c->products()->count() }}</td>
                                                                <td class="text-middle">
                                                                    <a href="javascript:void(0)"  class="btn btn-outline-warning" style="" id="Catedit{{ $c->id }}">Edit</a>
                                                                
                                                                    <form action="{{ route('tags.destroy',$c->id) }}" method="POST" style="display:inline">
                                                                        {{ csrf_field() }}
                                                                        <input hidden name="_method" value="DELETE"/>
                                                                        <button type="button" id="deleteCat{{ $c->id }}" class="btn btn-outline-danger">Delete</button>
                                                                    </form>

                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

@section('js')

<script type="text/javascript">
    $(document).ready(function() {
        $("[id*='Catedit']").click(function(){
            var id = $(this).attr("id").slice(7);
            $('#categoryName'+id).attr("hidden","true");
            $("#CatupdateDiv"+id).removeAttr("hidden");
        });

        $("[id*='Catcancel']").click(function(){
            var id = $(this).attr("id").slice(9);
            $('#categoryName'+id).removeAttr("hidden");
            $("#CatupdateDiv"+id).attr("hidden","true");
        });
    });
</script>
@endsection