routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes(['verify' => true]);

// Route::get('/register/getEmail',function(){
//     return redirect('login');
// });



// Route::post('register/getEmail','Auth\LoginController@setEmail')->name('set_email');
// Route::get('signin/{provider}', 'Auth\LoginController@redirectToProvider');
// Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/blog/{alias}','Frontend\BlogController@post')->name('blog');
Route::get('/blog','Frontend\BlogController@index');

Route::get('/', 'Frontend\PageController@home')->name('home');
Route::get('/landing3', 'Frontend\PageController@index3')->name('home');
Route::get('/landing4', 'Frontend\PageController@index4')->name('home');

Route::get('home', 'Frontend\PageController@home');

Route::get('/clients','Frontend\PageController@clients');
Route::post('newsletter/subscribe','Frontend\PageController@NewsLetter')->name('newsletter.subscribe');
Route::get('/category/{slug}/{sub_slug}','Frontend\PageController@category');
Route::get('/category/{slug}','Frontend\PageController@category');
Route::get('/about-us', 'Frontend\PageController@about');
Route::get('/privacy-policy', 'Frontend\PageController@privacyPolicy');
Route::get('/terms-and-conditions', 'Frontend\PageController@termsAndConditions');
Route::get('/inquiry', 'Frontend\PageController@inquiry');
Route::post('/inquiry/submit', 'Frontend\PageController@inquirySubmit');



// Route::get('/shop','Frontend\PageController@shop');

Route::get('/shop/{category_slug?}','Frontend\PageController@shop')->name('shop');

Route::get('/products/{slug}','Frontend\PageController@products');

Route::get('/search','Frontend\PageController@Search');
Route::get('/testimonials','Frontend\PageController@testimonials');
// Route::get('/contact',function(){
//     return view('frontend.contact');
// });
// Route::get('/about',function(){
//     $testimonials= Testimonial::all();
//     return view('frontend.about')->with('testimonials',$testimonials);
// });

Route::get('/cart','Frontend\CartController@cart');

Route::post('/cart/additem','Frontend\CartController@addItem');
Route::post('/cart/removeitem/{rowId}','Frontend\CartController@removeItem');
Route::post('/cart/emptycart','Frontend\CartController@emptyCart');
Route::post('/cart/updateqty','Frontend\CartController@updateQty');

Route::post('/checkout','Frontend\CheckoutController@shippingInformation');
Route::get('/checkout','Frontend\CheckoutController@summary');

Route::post("/payment/paypal", 'Frontend\CheckoutController@payWithPaypal');
Route::post("/payment/paypal/return", 'Frontend\CheckoutController@getPaypalPaymentStatus');

Route::get('payment/{code}','Frontend\CheckoutController@payment')->name('payment');
Route::post('payment/{code}','Frontend\CheckoutController@paymentSuccess')->name('payment');

Route::get('/order/{slug}','Frontend\PageController@Order');

Route::post('post/message','Frontend\PageController@Feedback')->name('contact.us');
Route::post('post/order','Frontend\PageController@GeneralOrder')->name('general.order');


// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/test', 'HomeController@index');

// Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
// Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
// Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');



Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');
    
    Route::get('manage/categories','Admin\CategoryController@index')->name('category.index');
    Route::get('manage/infos','Admin\InfoController@index')->name('infos.index');


    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    Route::post('settings/edit-socials','Admin\SettingsController@editSocials')->name('admin.settings.editSocials');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');
    
    //order Routes
    Route::get('quotations/all','Admin\QuotationController@allQuotations')->name('all.quotations');
    Route::post('quotations/delete','Admin\AdminController@DeleteQuotation')->name('delete.quotation');
    Route::get('quotations/export','Admin\QuotationController@export')->name('quotations.export');
    Route::get('quotations/{id}','Admin\AdminController@ShowQuotation')->name('show.quotation');
    Route::get('quotations','Admin\QuotationController@index')->name('quotations.index');
    Route::get('getUnseenQuotationCount','Admin\QuotationController@getUnseenOrderCount')->name('getUnseenQuotationCount');
    Route::get('getUnseenQuotation','Admin\QuotationController@getUnseenOrder')->name('getUnseenQuotation');
    Route::post('markseen/quotation','Admin\QuotationController@MarkSeen');

    Route::get('orders/all','Admin\OrderController@allOrders')->name('all.orders');
    Route::delete('orders/{id}/delete','Admin\AdminController@DeleteOrder')->name('orders.destroy');
    Route::get('orders/export','Admin\OrderController@export')->name('orders.export');
    Route::get('orders/{id}','Admin\AdminController@ShowOrder')->name('show.order');
    Route::patch('orders/{id}','Admin\OrderController@update')->name('orders.update');
    Route::get('orders','Admin\OrderController@index')->name('orders.index');
    Route::get('getUnseenOrderCount','Admin\OrderController@getUnseenOrderCount')->name('getUnseenOrderCount');
    Route::get('getUnseenOrder','Admin\OrderController@getUnseenOrder')->name('getUnseenOrder');
    Route::post('markseen/order','Admin\OrderController@MarkSeen');

    Route::resource('blogs', 'Admin\BlogController',['except' => ['create']]);

    Route::post('/testimonials/update-status','Admin\TestimonialController@updateStatus')->name('testimonials.activate');
    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::post('pages/{page}/update','Admin\PageController@update')->name('pages.update');
    Route::get('pages','Admin\PageController@index')->name('pages.index');

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');

    Route::get('/','Admin\AdminController@index');
    
    //Category routes
    
    Route::post('/manage/categories','Admin\CategoryController@StoreCat')->name('category.add');
    Route::get('/edit/category/{id}','Admin\CategoryController@EditCat')->name('category.edit');
    Route::post('/update/category/{id}','Admin\CategoryController@UpdateCat')->name('category.update');
    Route::post('/delete/category/{id}','Admin\CategoryController@DestroyCat')->name('category.delete');
    
    Route::post('/edit/info','Admin\InfoController@EditInfo')->name('info.edit');
    
    
    Route::get('manage/clients','Admin\ClientController@index');

    Route::post('/manage/clients','Admin\ClientController@StoreCat')->name('client.add');
    Route::post('/edit/client','Admin\ClientController@EditCat')->name('client.edit');

resources/views/admin/partials/footer.blade.php
</div>
</div>


<!-- BEGIN VENDOR JS-->

<script src="{{asset('admin-assets/app-assets/js/core/libraries/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/tether.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/js/core/libraries/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/unison.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/blockUI.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/jquery.matchHeight-min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/ui/screenfull.min.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/vendors/js/extensions/pace.min.js')}}" type="text/javascript"></script>
<!-- BEGIN VENDOR JS-->
<!-- BEGIN PAGE VENDOR JS-->
<script src="{{asset('admin-assets/app-assets/vendors/js/charts/chart.min.js')}}" type="text/javascript"></script>
<!-- END PAGE VENDOR JS-->
<!-- BEGIN PAGE VENDOR JS-->
<script src="{{asset('admin-assets/app-assets/vendors/js/gallery/masonry/masonry.pkgd.min.js')}}" type="text/javascript"></script>
<!-- END PAGE VENDOR JS-->
<!-- BEGIN ROBUST JS-->
<script src="{{asset('admin-assets/app-assets/js/core/app-menu.js')}}" type="text/javascript"></script>
<script src="{{asset('admin-assets/app-assets/js/core/app.js')}}" type="text/javascript"></script>
<!-- END ROBUST JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('admin-assets/app-assets/js/scripts/gallery/photo-swipe/photoswipe-script.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('admin-assets/app-assets/js/scripts/pages/dashboard-lite.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->
<script src="{{asset('sweetprompt/lib/sweetalert2.min.js')}}" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js" type="text/javascript"></script>

<script>
  $("[id*='delete']").click(function(e){
    var ele = this;
    e.preventDefault();
    
    swal({
      title: "Are you sure?",
      text: "You will not be able to recover this record!",
      type: "warning",

      showCancelButton: true,

    }).then(function(){
      ele.form.submit();
    }).catch(swal.noop);

  });
</script>
@yield('js');
@include('admin.partials.messages');

<script type="text/javascript">
  $(document).ready(function(){
    var url = window.location.href.split('?')[0];
    var url = url.split("/").splice(0, 6);
    
    var action=url[4];
    if(!action || action == '')
      action = 'dashboard';
    
    if($('#'+action).attr('class')!='nav-item hidden')
    {
      $('#'+action).attr('class','nav-item active');
    }
    
  });
</script>

<script>
  function getUnseenQuoteCount(){
    Pace.ignore(function(){ 
      $.get("{{ route('getUnseenQuotationCount') }}",
        function(data,status){
            $("#rno1" ).text(data.ordercount); 
        }
      );
    });
  }

  function getUnseenMsgCount(){
    Pace.ignore(function(){ 
      $.get("{{ route('getUnseenMsgCount') }}",
        function(data,status){
            $("#mno1" ).text(data.mno);  
        }
      );
    });
  }


  function getUnseenOrder(){
    $('#Qnotis').append('<div class="text-xs-center" style="margin:20px"><img src="/img/loading.gif"/></div>');
    $.get("{{ route('getUnseenOrder') }}",
      function(data,status){
          $("#qno1" ).text(data.ordercount);
          $("#qno2" ).text(data.ordercount+" New");

          $('#Qnotis').empty();
          $('#Qnotis').append(data.html);
          $('#Qnotis').perfectScrollbar('update');
      }
    );
  }

  function getUnseenQuote(){
    $('#Qnotis').append('<div class="text-xs-center" style="margin:20px"><img src="/img/loading.gif"/></div>');
    $.get("{{ route('getUnseenQuotation') }}",
      function(data,status){
          $("#rno1" ).text(data.ordercount);
          $("#rno2" ).text(data.ordercount+" New");

          $('#Rnotis').empty();
          $('#Rnotis').append(data.html);
          $('#Rnotis').perfectScrollbar('update');
      }
    );
  }

  function getUnseenMsg(){
    $('#Mnotis').append('<div class="text-xs-center" style="margin:20px"><img src="/img/loading.gif"/></div>');        
    $.get("{{ route('getUnseenMsg') }}",
      function(data,status){
          $("#mno1" ).text(data.mno);
          $("#mno2" ).text(data.mno+" New");

          $('#Mnotis').empty();
          $('#Mnotis').append(data.html);
          $('#Mnotis').perfectScrollbar('update');
      }
    );
  }
</script>

</body>
</html>

resources/views/admin/partials/mnotis.blade.php
@if($mno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new messages</p>
@endif
@foreach($messages as $m)
    <?php 
    $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($m->created_at))->diffForHumans();
    ?>
    <a href="{{ route('contact-us-messages.show',$m->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="/admin-assets/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar"><i></i></span></div>
        <div class="media-body">
        <h6 class="media-heading">{{ $m->name }}</h6>
        <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">Says "{{ $m->subject }}"</p><small>
            <time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach

resources/views/admin/partials/navbar.blade.php
<body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns  fixed-navbar">

  <!-- navbar-fixed-top-->
  <nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li class="nav-item mobile-menu hidden-md-up float-xs-left"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5 font-large-1"></i></a></li>
          <li class="nav-item"><a href="" class="navbar-brand nav-link"><img alt="Bagbox" src="{{asset('/logo.png')}}" style="height:4rem" class="brand-logo"></a></li>
          <li class="nav-item hidden-md-up float-xs-right"><a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i></a></li>
        </ul>
      </div>
      <div class="navbar-container content container-fluid">
        <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
          <ul class="nav navbar-nav">
            <li class="nav-item hidden-sm-down"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5">         </i></a></li>
            {{-- <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li> --}}
          </ul>
          <ul class="nav navbar-nav float-xs-right">

            <li class="dropdown dropdown-notification nav-item"><a href="#" data-toggle="dropdown" class="nav-link nav-link-label" onclick="getUnseenOrder()"><i class="ficon icon-bell4"></i><span class="tag tag-pill tag-default tag-danger tag-default tag-up" id="qno1">{{ $ordercount }}</span></a>
                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                  <li class="dropdown-menu-header">
                    <h6 class="dropdown-header m-0"><span class="grey darken-2">Orders</span><span class="notification-tag tag tag-default tag-danger float-xs-right m-0" id="qno2">{{ $ordercount }} New</span></h6>
                  </li>
                  <li class="list-group scrollable-container" id="Qnotis">
                    
                  </li>
                  <li class="dropdown-menu-footer"><a href="/admin/orders" class="dropdown-item text-muted text-xs-center">View all new orders</a></li>
                </ul>
              </li>
              <li class="dropdown dropdown-notification nav-item"><a href="#" data-toggle="dropdown" class="nav-link nav-link-label" onclick="getUnseenQuote()"><i class="ficon icon-bell2"></i><span class="tag tag-pill tag-default tag-danger tag-default tag-up" id="rno1">{{ $quotationcount }}</span></a>
                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                  <li class="dropdown-menu-header">
                    <h6 class="dropdown-header m-0"><span class="grey darken-2">Quotation Orders</span><span class="notification-tag tag tag-default tag-danger float-xs-right m-0" id="rno2">{{ $quotationcount }} New</span></h6>
                  </li>
                  <li class="list-group scrollable-container" id="Rnotis">
                    
                  </li>
                  <li class="dropdown-menu-footer"><a href="/admin/quotations" class="dropdown-item text-muted text-xs-center">Show all quotation orders</a></li>
                </ul>
              </li>
            
            
            <li class="dropdown dropdown-user nav-item"><a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link"><span class="avatar avatar-online"><img src="{{ route('optimize', ['img','avatar.png',30,30]) }}" alt="avatar"><i></i></span><span class="user-name" id="adminName">{{ Auth::guard('admin_user')->user()->name }}</span></a>
              <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('profile') }}" class="dropdown-item"><i class="icon-head"></i> Edit Profile</a>
                <div class="dropdown-divider"></div>
                <a href="{{ url('/admin/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item">
                <i class="icon-power3"></i> Logout</a>
                <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
                </form>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <!-- ////////////////////////////////////////////////////////////////////////////-->


  <!-- main menu-->
  <div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
    <!-- main menu content-->
    <div class="main-menu-content">
      <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
        <br>
        <li id="dashboard" class="nav-item "><a href="{{URL::to('admin/')}}"><i class="icon-home3"></i><span data-i18n="nav.dash.main" class="menu-title">Dashboard</span></a>
        </li>

        <li id="managecategories" class="@if(Request::is('admin/manage/categories')) active @endif nav-item "><a href="{{URL::to('admin/manage/categories')}}"><i class="icon-ios-list"></i><span data-i18n="nav.staffs.main" class="menu-title">Manage Categories</span></a>
        </li>
        <li id="manageclients" class="@if(Request::is('admin/manage/clients')) active @endif nav-item "><a href="{{URL::to('admin/manage/clients')}}"><i class="icon-ios-list"></i><span data-i18n="nav.staffs.main" class="menu-title">Manage Clients</span></a>
        </li>
        
        <li id="tags" class="nav-item "><a href="{{ route('tags.index') }}"><i class="icon-tags"></i><span data-i18n="nav.tags" class="menu-title">Tags</span></a>
        </li>

        <li id="products" class="nav-item"><a href="{{ route('products.index') }}"><i class="icon-cart3"></i><span data-i18n="nav.albums.main" class="menu-title">Manage Products</span></a>
        </li> 

        <li id="deliveryzones" class="nav-item "><a href="{{ route('delivery_zones.index') }}"><i class="icon-truck"></i><span data-i18n="nav.deliveryzones.main" class="menu-title">Delivery Zones</span></a>
        </li>

        <li id="infos" class="nav-item"><a href="{{ route('infos.index') }}"><i class="icon-tags"></i><span data-i18n="nav.albums.main" class="menu-title">Manage Infos</span></a>
        </li> 

        <li id="orders" class="nav-item "><a href="{{ route('orders.index') }}"><i class="icon-at2"></i><span data-i18n="nav.orders" class="menu-title">Orders</span></a>
        </li>

        <li id="quotations" class="nav-item "><a href="{{ route('quotations.index') }}"><i class="icon-at2"></i><span data-i18n="nav.quotations" class="menu-title">Quotations</span></a>
        </li>

        <li id="blogs" class="nav-item "><a href="{{ route('blogs.index') }}"><i class="icon-list-alt"></i><span data-i18n="nav.blogs" class="menu-title">News/Events</span></a>
        </li>

        {{-- <li id="albums" class="nav-item "><a href="{{ route('albums.index') }}"><i class="icon-image3"></i><span data-i18n="nav.albums.main" class="menu-title">Albums</span></a>
        </li> --}}

        {{-- <li id="newsletter" class="nav-item "><a href="{{ route('newsletter') }}"><i class="icon-mail6"></i><span data-i18n="nav.newsletter.main" class="menu-title">Newsletter</span></a>
        </li> --}}
        <li id="downloads" class="nav-item "><a href="{{ route('downloads.index') }}"><i class="icon-download"></i><span data-i18n="nav.downloads.main" class="menu-title">Downloads</span></a>
        </li>

        <li id="testimonials" class="nav-item "><a href="{{ route('testimonials.index') }}"><i class="icon-commenting"></i><span data-i18n="nav.testimonials.main" class="menu-title">Testimonials</span></a>
        </li>

        {{-- <li id="contact-us-messages" class="nav-item "><a href="{{ route('contact-us-messages.index') }}"><i class="icon-at2"></i><span data-i18n="nav.contact-us-messages.main" class="menu-title">Contact Messages</span></a>
        </li> --}}
        <li id="pages" class="nav-item "><a href="{{ route('pages.index') }}"><i class="icon-ios-list"></i><span data-i18n="nav.pages.main" class="menu-title">Pages</span></a>
        </li>

        <li id="settings" class="nav-item "><a href="{{ route('admin.settings') }}"><i class="icon-gear"></i><span data-i18n="nav.settings.main" class="menu-title">Settings</span></a>
        </li>

        <li class="nav-item has-sub"><a href="#"><i class="icon-gear"></i><span data-i18n="nav.maps.main" class="menu-title">SEO Page Settings</span></a>
          <ul class="menu-content" style="">
            <li id="home_page_settings" class="is-shown {{ Request::is('*seo-settings/home_page_settings') ? 'active' : '' }}"><a href="{{ route('admin.seo-settings' , 'home_page_settings') }}" data-i18n="nav.settings.seo" class="menu-item">Home Page Settings</a>
            </li>
            <li id="shop_page_settings" class="is-shown {{ Request::is('*seo-settings/shop_page_settings') ? 'active' : '' }}"><a href="{{ route('admin.seo-settings' , 'shop_page_settings') }}" data-i18n="nav.settings.seo" class="menu-item">Shop Page Settings</a>
            </li>
            <li id="clients_page_settings" class="is-shown {{ Request::is('*seo-settings/clients_page_settings') ? 'active' : '' }}"><a href="{{ route('admin.seo-settings' , 'clients_page_settings') }}" data-i18n="nav.settings.seo" class="menu-item">Clients Page Settings</a>
            </li>
            <li id="blog_page_settings" class="is-shown {{ Request::is('*seo-settings/blog_page_settings') ? 'active' : '' }}"><a href="{{ route('admin.seo-settings' , 'blog_page_settings') }}" data-i18n="nav.settings.seo" class="menu-item">Blog Page Settings</a>
            </li>
            <li id="testimonials_page_settings" class="is-shown {{ Request::is('*seo-settings/testimonials_page_settings') ? 'active' : '' }}"><a href="{{ route('admin.seo-settings' , 'testimonials_page_settings') }}" data-i18n="nav.settings.seo" class="menu-item">Testimonials Page Settings</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /main menu content-->
    <!-- main menu footer-->
    <!-- include includes/menu-footer-->
    <!-- main menu footer-->
  </div>
  <!-- / main menu-->
  <div class="app-content content container-fluid">
      <div class="content-wrapper">
        
         @if (count($errors)>0 )
          <div class="alert alert-dismissible fade in mb-2">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true" style="color:black">&times;</span>
            </button>
            <ul class="list-group">
              @foreach ($errors->all() as $error)
                <li class="list-group-item list-group-item-danger">{{ $error }}</li>
              @endforeach
            </ul>
          </div>	
        @endif 